# Generated by Django 4.2 on 2023-04-17 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=34)),
                ("amount", models.IntegerField()),
                ("due_date", models.DateField(default=datetime.date.today)),
                ("vs", models.CharField(max_length=10)),
                ("ss", models.CharField(max_length=10)),
                ("cs", models.CharField(max_length=4)),
                ("payment_note", models.CharField(max_length=99)),
                ("beneficiary_name", models.CharField(max_length=99)),
                ("beneficiary_address1", models.CharField(max_length=99)),
                ("beneficiary_address2", models.CharField(max_length=99)),
            ],
        ),
    ]
