# Generated by Django 4.2 on 2023-04-18 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pmb", "0003_alter_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
