# Generated by Django 4.2 on 2023-05-05 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmb", "0004_payment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="beneficiary_address1",
            field=models.CharField(blank=True, default="", max_length=99),
        ),
        migrations.AlterField(
            model_name="payment",
            name="beneficiary_address2",
            field=models.CharField(blank=True, default="", max_length=99),
        ),
        migrations.AlterField(
            model_name="payment",
            name="beneficiary_name",
            field=models.CharField(blank=True, default="", max_length=99),
        ),
        migrations.AlterField(
            model_name="payment",
            name="constant_symbol",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_note",
            field=models.CharField(blank=True, default="", max_length=99),
        ),
        migrations.AlterField(
            model_name="payment",
            name="specific_symbol",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="variable_symbol",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
